spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerbank?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml 